# This pipeline automates the following processes:
#  1) Build a production version of the client side using the latest commit of the main branch
#  2) Publish the new build in local working directory
#  3) Deploy the new build to a Azure Static Web App

trigger:
- main

# resources:
# - repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndPublish
  displayName: Build and publish React artifacts
  jobs:
  - job: BuildAndPublish
    displayName: Build and publish React artifacts
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '18.x'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npm run build
      displayName: 'Build React app'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        pathtoPublish: 'build'
        artifactName: 'build'

- stage: Deploy
  displayName: Deploy React app to Azure Static Web App
  jobs:
  - job: Deploy
    displayName: Deploy React app to Azure Static Web App
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureStaticWebApp@0
      displayName: 'Deploy build to Azure Static Web App'
      inputs:
        app_location: '/build'
        skip_app_build: true
        azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)