# This pipeline automates the following processes:
#  1) Build a production version of the client side using the latest commit of the main branch
#  2) Deploy the new image to a Azure Static Web App

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureStaticWebApp: 'your_static_web_app_name'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build React app'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    pathtoPublish: 'build'
    artifactName: 'build'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  inputs:
    app_location: '/build'
    skip_app_build: true
    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)